server:
  port: 80

country: China

user1:
  name: zhangsan
  age: 18


likes:
  - ball
  - sleep
  - play

likes2: [ ball,sleep,play ]

users:
  - name: zhangsan
    age: 18
  - name: lisi
    age: 22


users2: [ { name:zhangsan,age:18 },{ name:lisi,age:22 } ]

base:
  dir: c:\win10

tempDir: ${base.dir}\temp


datasource:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost/springboot_db
  username: root
  password: root666